spring:
  jpa:
    properties:
      hibernate:
          hbm2ddl.auto: validate
          show_sql: true
          format_sql: false
          use_sql_comments: false
liquibase:
  change-log: classpath:/db/changelog/master.xml

signing:
  key: "345345fsdfsf5345"
