example:
  property: "I AM IN THE DEFAULT"

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"

spring:
  jpa:
    properties:
      hibernate:
          hbm2ddl.auto: validate
          show_sql: false
          format_sql: false
          use_sql_comments: false
liquibase:
  change-log: classpath:/db/changelog/master.xml

